export const EMAIL = `piring@shinki.id
diamond@shinki.id
floor@shinki.id
fan@shinki.id
tangga@shinki.id
jude@shinki.id
nichole@shinki.id
phoetic@shinki.id
shadow@shinki.id
monarch@shinki.id
drum@shinki.id
nada@shinki.id
sung@shinki.id
blade@shinki.id
agung@shinki.id
ruler@shinki.id
dragon@shinki.id
twinning@shinki.id
bass@shinki.id
naruto@shinki.id
sheis@shinki.id
minato@shinki.id
kushina@shinki.id
luffy@shinki.id
burner@shinki.id
cipaws@shinki.id
clarinet@shinki.id
over@shinki.id
zoro@shinki.id
sanji@shinki.id
mendy@shinki.id
nami@shinki.id
piano@shinki.id
ussop@shinki.id
laci@shinki.id
frankie@shinki.id
brook@shinki.id
high@shinki.id
plain@shinki.id
magic@shinki.id
carribean@shinki.id
chopper@shinki.id
chess@shinki.id
bordes@shinki.id
modric@shinki.id
flashen@shinki.id
golden@shinki.id
robbin@shinki.id
cheeky@shinki.id
juice@shinki.id
lyone@shinki.id
jinbei@shinki.id
hazel@shinki.id
mackoss@shinki.id
fast@shinki.id
pedro@shinki.id
cashes@shinki.id
advane@shinki.id
hooke@shinki.id
anis@shinki.id
meja@shinki.id
cama@shinki.id
clover@shinki.id
view@shinki.id
time@shinki.id
loudly@shinki.id
seirra@shinki.id
frappucino@shinki.id
staff@shinki.id
cuirras@shinki.id
ice@shinki.id
middle@shinki.id
clown@shinki.id
snappy@shinki.id
checkout@shinki.id
quas@shinki.id
kepa@shinki.id
kaca@shinki.id
shire@shinki.id
kursi@shinki.id
lotus@shinki.id
wex@shinki.id
nuudle@shinki.id
brahim@shinki.id
snowrio@shinki.id
orb@shinki.id
smooth@shinki.id
flamingo@shinki.id
luka@shinki.id
himatse@shinki.id
fran@shinki.id
point@shinki.id
section@shinki.id
carol@shinki.id
beach@shinki.id
argada@shinki.id
alanaz@shinki.id
latte@shinki.id
doucle@shinki.id
nadle@shinki.id
spouse@shinki.id
choice@shinki.id
fooled@shinki.id
gressey@shinki.id
browe@shinki.id
hylost@shinki.id
maxim@shinki.id
frost@shinki.id
botol@shinki.id
parses@shinki.id
tamme@shinki.id
rewinds@shinki.id
sinnergy@shinki.id
cabbin@shinki.id
omicko@shinki.id
crochs@shinki.id
barbars@shinki.id
moving@shinki.id
villes@shinki.id
garcia@shinki.id
door@shinki.id
ryse@shinki.id
stage@shinki.id
luxury@shinki.id
cleo@shinki.id
maters@shinki.id`